// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZtKKNFvhTGDqymrKcXAZ0-iCjWFlnYQ',
    appId: '1:641958548853:web:b923c6de5a2d4fb162ef3c',
    messagingSenderId: '641958548853',
    projectId: 'fluttergram-80763',
    authDomain: 'fluttergram-80763.firebaseapp.com',
    storageBucket: 'fluttergram-80763.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmE6vqWQpOkZl4QoTAL1lwdWZzHXScGa8',
    appId: '1:641958548853:android:a1da311df422ef8062ef3c',
    messagingSenderId: '641958548853',
    projectId: 'fluttergram-80763',
    storageBucket: 'fluttergram-80763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVtFbx_aP3G16sZHX3w5IXOYDCv9py0k',
    appId: '1:641958548853:ios:13f8eb5231c684c262ef3c',
    messagingSenderId: '641958548853',
    projectId: 'fluttergram-80763',
    storageBucket: 'fluttergram-80763.appspot.com',
    iosClientId: '641958548853-9ph1jo05ecqfrsiuurpcbvko444900or.apps.googleusercontent.com',
    iosBundleId: 'com.toygram.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKVtFbx_aP3G16sZHX3w5IXOYDCv9py0k',
    appId: '1:641958548853:ios:cc2914707836767062ef3c',
    messagingSenderId: '641958548853',
    projectId: 'fluttergram-80763',
    storageBucket: 'fluttergram-80763.appspot.com',
    iosClientId: '641958548853-epdokpu077drirsll2pva9tf2icp9pa3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
